version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: qou-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qou_coffee
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d qou_coffee"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  backend:
    build:
      context: ./backend
    container_name: qoyu-backend
    env_file:
      - ./backend/.env           
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media:/media
    restart: always

web:
  build:
    context: ./frontend
    args: { VITE_API_URL: /api }
  container_name: qoyu-web
  depends_on: [backend]
  restart: always
  # ports:    # <-- убрать, порты будет открывать Caddy
  #   - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  
  
caddy:
  image: caddy:2.7-alpine
  container_name: qou-caddy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile:ro
    - caddy_data:/data
    - caddy_config:/config
  depends_on: [web, backend]
  restart: always
volumes:
  pg_data:
  media:
